name: ci

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      QUMA_TEST_DRIVERS: sqlite,mysql,pgsql
      QUMA_DB_MYSQL_HOST: localhost
      QUMA_DB_PGSQL_HOST: localhost
      QUMA_DB_NAME: quma_db
      QUMA_DB_USER: root
      QUMA_DB_PASSWORD: root
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: '8.5'
          extensions: mysql, pgsql, sqlite3
          coverage: xdebug

      - name: Checkout repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Install packages with composer
        run: composer install

      - name: Start mysql server and create test db
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE `${{ env.QUMA_DB_NAME }}`;' -u${{ env.QUMA_DB_USER }} -p${{ env.QUMA_DB_PASSWORD }}

      - name: Start postgresql server and create test db
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createdb ${{ env.QUMA_DB_NAME }}
          sudo -u postgres psql -c "CREATE USER ${{ env.QUMA_DB_USER }} WITH SUPERUSER PASSWORD '${{ env.QUMA_DB_PASSWORD }}';"

      - name: Run PHP lint checks
        run: composer lint

      - name: Run Markdown lint checks
        run: composer docs:lint
        env:
          npm_config_yes: 'true'

      - name: Run tests with coverage
        run: composer coverage:test

      - name: Analyze coverage
        run: composer coverage:analyze

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage/coverage.xml
          fail_ci_if_error: true

      - name: Run static type checks
        run: composer types -- --output-format=github --shepherd
